BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Clientes" (
	"Id_cliente"	INTEGER NOT NULL,
	"Nombre_usuario"	TEXT NOT NULL UNIQUE,
	"Nombre"	TEXT NOT NULL,
	"Apellido"	TEXT NOT NULL,
	"Vip"	INTEGER NOT NULL,
	PRIMARY KEY("Id_cliente" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Peliculas" (
	"Id_Pelicula"	INTEGER NOT NULL,
	"Nombre_Pelicula"	TEXT NOT NULL,
	"Genero"	TEXT NOT NULL,
	"Idioma"	TEXT NOT NULL,
	PRIMARY KEY("Id_Pelicula" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Salas" (
	"Id_Sala"	INTEGER NOT NULL,
	"Nombre_Sala"	TEXT NOT NULL UNIQUE,
	"Tipo"	TEXT NOT NULL,
	"Capacidad"	INTEGER NOT NULL,
	"Precio"	REAL NOT NULL,
	PRIMARY KEY("Id_Sala" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Descuentos" (
	"Id_Descuento"	INTEGER NOT NULL,
	"Tipo_Sala"	TEXT NOT NULL,
	"Dia"	TEXT NOT NULL,
	"Descuento"	REAL NOT NULL,
	PRIMARY KEY("Id_Descuento" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Reservas" (
	"Id_Cliente"	INTEGER NOT NULL,
	"Id_Sala"	INTEGER NOT NULL,
	"Id_Reserva"	INTEGER NOT NULL,
	"Id_Pelicula"	INTEGER NOT NULL,
	"Precio"	REAL NOT NULL,
	PRIMARY KEY("Id_Reserva" AUTOINCREMENT)
);
COMMIT;
